# Generated by Django 3.0.6 on 2020-06-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20200607_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
