# Generated by Django 3.0.6 on 2020-07-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_womens'),
    ]

    operations = [
        migrations.AddField(
            model_name='womens',
            name='detailimage2',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='womens',
            name='detailimage3',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='womens',
            name='detailimage4',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
