# Generated by Django 3.0.6 on 2020-07-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0003_auto_20200629_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailimage',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
